version: '3.8'

services:
  backend:
    build: ./backend
    container_name: api
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: tppe
      POSTGRES_PASSWORD: escondidinho
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: