services:
  backend:
    build: ./backend
    container_name: api
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/app
      - ./backend/tests:/app/tests
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ui
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: tppe
      POSTGRES_PASSWORD: escondidinho
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: