"""Initial migration

Revision ID: f246b0caadac
Revises: b39975bf0d12
Create Date: 2025-06-26 22:12:13.401623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f246b0caadac'
down_revision = 'b39975bf0d12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('max_pessoas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('despesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('pagador_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['pagador_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_mercado', sa.String(length=100), nullable=True),
    sa.Column('itens', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['despesas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imoveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endereco', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['despesas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imoveis')
    op.drop_table('compras')
    op.drop_table('despesas')
    op.drop_table('pessoas')
    op.drop_table('grupos')
    # ### end Alembic commands ###
